// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PasswordReset struct {
	ID        pgtype.UUID
	UserID    pgtype.UUID
	CodeHash  string
	ExpiresAt pgtype.Timestamptz
	Used      pgtype.Bool
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID            pgtype.UUID
	Username      pgtype.Text
	Email         string
	EmailVerified bool
	PasswordHash  string
	FirstName     string
	LastName      pgtype.Text
	Bio           pgtype.Text
	AvatarUrl     pgtype.Text
	LastSeen      pgtype.Timestamptz
	IsOnline      bool
	IsDeleted     bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}
